# Generated by Django 3.1 on 2020-08-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='acc_type',
            field=models.CharField(default='basic', max_length=40),
            preserve_default=False,
        ),
    ]
