# Generated by Django 3.1 on 2020-08-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
