# Generated by Django 3.1 on 2020-08-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qtitle', models.CharField(max_length=100)),
                ('Qdesc', models.CharField(max_length=300)),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('img4', models.ImageField(upload_to='images/')),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qapp.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adesc', models.CharField(max_length=500)),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('img4', models.ImageField(upload_to='images/')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qapp.question')),
            ],
        ),
    ]
