# Generated by Django 3.1 on 2020-08-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0005_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Qdesc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Qtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
