# Generated by Django 3.1 on 2020-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0006_auto_20200831_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Qdesc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Qtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
