# Generated by Django 3.1 on 2020-08-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0007_auto_20200831_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Qtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.accounts'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
