# Generated by Django 3.1 on 2020-08-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0008_auto_20200831_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.accounts'),
        ),
    ]
