# Generated by Django 3.1 on 2020-09-09 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0010_auto_20200902_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='asked_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
